close all
clear

%% load data

load Batch_Records1.mat Batch_Records1
load Batch_Records2.mat Batch_Records2

%% rearrange data

Fs_temp = [Batch_Records1.Batch_01.Fs.y Batch_Records1.Batch_02.Fs.y ...
    Batch_Records1.Batch_03.Fs.y Batch_Records1.Batch_04.Fs.y ...
    Batch_Records1.Batch_05.Fs.y Batch_Records1.Batch_06.Fs.y ...
    Batch_Records1.Batch_07.Fs.y Batch_Records1.Batch_08.Fs.y ...
    Batch_Records1.Batch_09.Fs.y Batch_Records1.Batch_10.Fs.y ...
    Batch_Records1.Batch_11.Fs.y Batch_Records1.Batch_12.Fs.y ...
    Batch_Records1.Batch_13.Fs.y Batch_Records1.Batch_14.Fs.y ...
    Batch_Records1.Batch_15.Fs.y Batch_Records1.Batch_16.Fs.y ...
    Batch_Records1.Batch_17.Fs.y Batch_Records1.Batch_18.Fs.y ...
    Batch_Records1.Batch_19.Fs.y Batch_Records1.Batch_20.Fs.y ...
    Batch_Records2.Batch_01.Fs.y Batch_Records2.Batch_02.Fs.y ...
    Batch_Records2.Batch_03.Fs.y Batch_Records2.Batch_04.Fs.y ...
    Batch_Records2.Batch_05.Fs.y Batch_Records2.Batch_06.Fs.y ...
    Batch_Records2.Batch_07.Fs.y Batch_Records2.Batch_08.Fs.y ...
    Batch_Records2.Batch_09.Fs.y Batch_Records2.Batch_10.Fs.y ...
    Batch_Records2.Batch_11.Fs.y Batch_Records2.Batch_12.Fs.y ...
    Batch_Records2.Batch_13.Fs.y Batch_Records2.Batch_14.Fs.y ...
    Batch_Records2.Batch_15.Fs.y Batch_Records2.Batch_16.Fs.y ...
    Batch_Records2.Batch_17.Fs.y Batch_Records2.Batch_18.Fs.y ...
    Batch_Records2.Batch_19.Fs.y Batch_Records2.Batch_20.Fs.y];
Fs = Fs_temp';

DO2_temp = [Batch_Records1.Batch_01.DO2.y Batch_Records1.Batch_02.DO2.y ...
    Batch_Records1.Batch_03.DO2.y Batch_Records1.Batch_04.DO2.y ...
    Batch_Records1.Batch_05.DO2.y Batch_Records1.Batch_06.DO2.y ...
    Batch_Records1.Batch_07.DO2.y Batch_Records1.Batch_08.DO2.y ...
    Batch_Records1.Batch_09.DO2.y Batch_Records1.Batch_10.DO2.y ...
    Batch_Records1.Batch_11.DO2.y Batch_Records1.Batch_12.DO2.y ...
    Batch_Records1.Batch_13.DO2.y Batch_Records1.Batch_14.DO2.y ...
    Batch_Records1.Batch_15.DO2.y Batch_Records1.Batch_16.DO2.y ...
    Batch_Records1.Batch_17.DO2.y Batch_Records1.Batch_18.DO2.y ...
    Batch_Records1.Batch_19.DO2.y Batch_Records1.Batch_20.DO2.y ...
    Batch_Records2.Batch_01.DO2.y Batch_Records2.Batch_02.DO2.y ...
    Batch_Records2.Batch_03.DO2.y Batch_Records2.Batch_04.DO2.y ...
    Batch_Records2.Batch_05.DO2.y Batch_Records2.Batch_06.DO2.y ...
    Batch_Records2.Batch_07.DO2.y Batch_Records2.Batch_08.DO2.y ...
    Batch_Records2.Batch_09.DO2.y Batch_Records2.Batch_10.DO2.y ...
    Batch_Records2.Batch_11.DO2.y Batch_Records2.Batch_12.DO2.y ...
    Batch_Records2.Batch_13.DO2.y Batch_Records2.Batch_14.DO2.y ...
    Batch_Records2.Batch_15.DO2.y Batch_Records2.Batch_16.DO2.y ...
    Batch_Records2.Batch_17.DO2.y Batch_Records2.Batch_18.DO2.y ...
    Batch_Records2.Batch_19.DO2.y Batch_Records2.Batch_20.DO2.y];
DO2 = DO2_temp';

P_temp = [Batch_Records1.Batch_01.P.y Batch_Records1.Batch_02.P.y ...
    Batch_Records1.Batch_03.P.y Batch_Records1.Batch_04.P.y ...
    Batch_Records1.Batch_05.P.y Batch_Records1.Batch_06.P.y ...
    Batch_Records1.Batch_07.P.y Batch_Records1.Batch_08.P.y ...
    Batch_Records1.Batch_09.P.y Batch_Records1.Batch_10.P.y ...
    Batch_Records1.Batch_11.P.y Batch_Records1.Batch_12.P.y ...
    Batch_Records1.Batch_13.P.y Batch_Records1.Batch_14.P.y ...
    Batch_Records1.Batch_15.P.y Batch_Records1.Batch_16.P.y ...
    Batch_Records1.Batch_17.P.y Batch_Records1.Batch_18.P.y ...
    Batch_Records1.Batch_19.P.y Batch_Records1.Batch_20.P.y ...
    Batch_Records2.Batch_01.P.y Batch_Records2.Batch_02.P.y ...
    Batch_Records2.Batch_03.P.y Batch_Records2.Batch_04.P.y ...
    Batch_Records2.Batch_05.P.y Batch_Records2.Batch_06.P.y ...
    Batch_Records2.Batch_07.P.y Batch_Records2.Batch_08.P.y ...
    Batch_Records2.Batch_09.P.y Batch_Records2.Batch_10.P.y ...
    Batch_Records2.Batch_11.P.y Batch_Records2.Batch_12.P.y ...
    Batch_Records2.Batch_13.P.y Batch_Records2.Batch_14.P.y ...
    Batch_Records2.Batch_15.P.y Batch_Records2.Batch_16.P.y ...
    Batch_Records2.Batch_17.P.y Batch_Records2.Batch_18.P.y ...
    Batch_Records2.Batch_19.P.y Batch_Records2.Batch_20.P.y];
P = P_temp';

%% quality attributions
P_final = P(:,end);

%% process data (OWTU unfolding)

% resampling (*5)
% Fs_select = 1:5:1150;
% Fs = Fs(:,Fs_select);
%     
% DO2_select = 1:5:1150;
% DO2 = DO2(:,DO2_select);
    
    
X = zeros(40,2300);
for i = 1:40
    for j = 1:1150
        X(i,(2*j-1):2*j) = [Fs(i,j) DO2(i,j)];
    end
end

%% centerlize

% X0 = zscore(X);
% Y0 = zscore(P_final);
X0 = X-mean(X);
Y0 = P_final - mean(P_final);

% save mean and std.V
Xm = mean(X);Ym = mean(P_final);
Xv = std(X); Yv = std(P_final);
for xx = 1:2300
    if Xv(xx) == 0
        Xv(xx) = 1;
    end
end

%% PLS modelling

[XL,YL,XS,YS,BETA,PCTVAR,MSE,stats] = plsregress(X0,Y0,5);
XR = XS*XL';
YR = XS*YL';

ErrorEllipse(XS(:,1:2),0.95,40,2)

%% model inversion
ydes = 25;
% ydes0 = (ydes-mean(P_final))/std(P_final);
ydes0 = ydes-mean(P_final);

% general inversion
tnew = ydes0*pinv(YL');

% null space
S = XS'*XS;
[U,~,~] = svd(S*YL');
G = U(:,2:end);
% lambda = ones(4,1);
% tnull = lambda'*G'*S;
%% offline matrix

D = tnew*XL';
H = G'*S*XL';
save datamat D H Xm Ym